apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: myappdevydb8h3.azurecr.io/frontend:727ccba57332c45672468c37ded616614ab082d7
        ports:
        - containerPort: 80
        env:
        - name: VITE_USER_API_URL
          value: "http://user-service:3001"
        - name: VITE_ORDER_API_URL
          value: "http://order-service:3002"
        - name: VITE_PAYMENT_API_URL
          value: "http://payment-service:3003"