apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: myappdevydb8h3.azurecr.io/user-service:727ccba57332c45672468c37ded616614ab082d7
        ports:
        - containerPort: 3001