apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: myappdevydb8h3.azurecr.io/user-service:ade12ebb914819539ff15aa1665e0ee37a70d77e
        ports:
        - containerPort: 3001