apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: myappdevydb8h3.azurecr.io/order-service:ade12ebb914819539ff15aa1665e0ee37a70d77e
        ports:
        - containerPort: 3002